{"name": "test_01_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'json'", "trace": "self = <testcase.operation.home.test_api.TestApi object at 0x000001CEC29F0A88>\noperation_fixture = None\n\n    def test_01_login(self, operation_fixture):\n        headers = {\"Content-Type\": \"application/json;charset=utf8\"}\n        url = \"http://testapi.intranet.aduer.com/common/v1/user/login\"\n        _data = {\n            \"password\": \"123456\",\n            \"phone\": \"15306501195\",\n            \"system\": \"operation\",\n            \"type\": \"password\"\n        }\n        res = requests.post(url=url, headers=headers, json=_data).json()\n>       print(res.json)\nE       AttributeError: 'dict' object has no attribute 'json'\n\ntestcase\\operation\\home\\test_api.py:16: AttributeError"}, "start": 1655294750229, "stop": 1655294750980, "uuid": "de3a09ad-bc87-45b4-b906-6fa24936bec3", "historyId": "f672f9c13fd2885cc386ecd68e2dadcf", "testCaseId": "b7339ec73a87d063a05a928081e480af", "fullName": "testcase.operation.home.test_api.TestApi#test_01_login", "labels": [{"name": "parentSuite", "value": "testcase.operation.home"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-FNPH2L6"}, {"name": "thread", "value": "22556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.operation.home.test_api"}]}